"""
PANDAS - DATAFRAME ATTRIBUTES AND METHODS

This file demonstrates how to inspect and understand
the structure of a Pandas DataFrame.

Attributes:
- shape
- columns
- index
- dtypes
- size
- ndim

Methods:
- head()
- tail()
- info()
- describe()
- count()
- nunique()
"""

In [2]:
import pandas as pd

Creating the dataset

In [4]:
orders = {
    "Order_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Customer": ["Amit", "Sneha", "Rahul", "Priya",
                 "Amit", "Neha", "Sneha", "Om"],
    "Product": ["Laptop", "Phone", "Mouse", "Keyboard",
                "Phone", "Laptop", "Mouse", "Monitor"],
    "Category": ["Electronics", "Electronics", "Accessories",
                 "Accessories", "Electronics", "Electronics",
                 "Accessories", "Electronics"],
    "Amount": [65000, 42000, 800, 1500, 45000, 72000, 900, 18000],
    "Quantity": [1, 1, 2, 1, 1, 1, 3, 1]
}

In [5]:
df = pd.DataFrame(orders)

In [6]:
df

   Order_ID Customer   Product     Category  Amount  Quantity
0       101     Amit    Laptop  Electronics   65000         1
1       102    Sneha     Phone  Electronics   42000         1
2       103    Rahul     Mouse  Accessories     800         2
3       104    Priya  Keyboard  Accessories    1500         1
4       105     Amit     Phone  Electronics   45000         1
5       106     Neha    Laptop  Electronics   72000         1
6       107    Sneha     Mouse  Accessories     900         3
7       108       Om   Monitor  Electronics   18000         1

In [9]:
#head()
df.head(2)

   Order_ID Customer Product     Category  Amount  Quantity
0       101     Amit  Laptop  Electronics   65000         1
1       102    Sneha   Phone  Electronics   42000         1

In [10]:
#tail()
df.tail(3)

   Order_ID Customer  Product     Category  Amount  Quantity
5       106     Neha   Laptop  Electronics   72000         1
6       107    Sneha    Mouse  Accessories     900         3
7       108       Om  Monitor  Electronics   18000         1

DataFrame Attributes

In [11]:
print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nIndex:")
print(df.index)

print("\nData Types:")
print(df.dtypes)

print("\nTotal Elements:")
print(df.size)

print("\nNumber of Dimensions:")
print(df.ndim)

Shape:
(8, 6)

Columns:
Index(['Order_ID', 'Customer', 'Product', 'Category', 'Amount', 'Quantity'], dtype='object')

Index:
RangeIndex(start=0, stop=8, step=1)

Data Types:
Order_ID     int64
Customer    object
Product     object
Category    object
Amount       int64
Quantity     int64
dtype: object

Total Elements:
48

Number of Dimensions:
2

Statistical Summary :

In [12]:
print("\nStatistical Summary:")
print(df.describe())

Statistical Summary:
        Order_ID        Amount  Quantity
count    8.00000      8.000000  8.000000
mean   104.50000  30650.000000  1.375000
std      2.44949  29302.169593  0.744024
min    101.00000    800.000000  1.000000
25%    102.75000   1350.000000  1.000000
50%    104.50000  30000.000000  1.000000
75%    106.25000  50000.000000  1.250000
max    108.00000  72000.000000  3.000000

In [13]:
#Count of Non-Null Values
print("\nNon-Null Count:")
print(df.count())


# --------------------------------------------------
# Number of Unique Customers
# --------------------------------------------------

print("\nNumber of Unique Customers:")
print(df["Customer"].nunique())


# --------------------------------------------------
# DataFrame Information
# --------------------------------------------------

print("\nDataFrame Information:")
df.info()

Non-Null Count:
Order_ID    8
Customer    8
Product     8
Category    8
Amount      8
Quantity    8
dtype: int64

Number of Unique Customers:
6

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  8 non-null      int64
 1   Customer  8 non-null      object
 2   Product   8 non-null      object
 3   Category  8 non-null      object
 4   Amount    8 non-null      int64
 5   Quantity  8 non-null      int64
dtypes: int64(3), object(3)
memory usage: 516.0+ bytes